config/routes.rb
Rails.application.routes.draw do

	root "home#top"
	get 'about' => "home#about"

#---users--
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :blogs, only: [:index, :new, :create, :show, :edit, :upadte, :destroy] do
		resources :comments, only: [:create]
	end
	resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user
	has_many :blog_comments, dependent: :delete_all

	validates :title, presence: true
	validates :body, presence: true
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
	validates :comment_text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

		has_many :blogs, dependent: :destroy
		has_many :blog_comments, dependent: :destroy
		attachment :profile_image

  validates :name, presence: true,
			length: { minimum: 4, maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resourse)
		user_path(current_user)
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
	end
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		blog = Blog.find(params[:blog_id])		#blog_idのカラムに関係する
		comment = current_user.blog_comments.new(blog_comment_params)	 	#ブログにコメントが作成される
		comment.blog_id = blog.id		#コメントのidとユーザーidは一緒
		comment.save
			flash[:success] = "コメントしました"
			redirect_to blog_path(blog)
	end

	private
	def blog_comment_params
		params.require(:comment).permit(:user_id, :blog_id, :comment_text)
	end

	def correct_blog_comment
		comment = BlogComment.find(params[:id])
		user = blog_comment.user
		unless user == current_user
			redirect_to(user_path)
		end
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_blog, only: [:edit, :update, :destroy]

	def index
		@blogs = Blog.all
		@user = current_user
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.user_id = current_user.id
		if @blog.save
			flash[:notice] = "ブログを投稿しました"
			redirect_to blog_path(@blog)
		else
			@user = current_user
			render :new
		end
	end

	def show
		@blog = Blog.find_by(id: params[:id])
		@user = @blog.user
		@blog_comment = BlogComment.new		#ブログ詳細ページでコメント投稿が出来るようにさせる
	end

	def edit
		@blog = Blog.find_by(id: params[:id])
	end

	def update
		@blog = Blog.find_by(id: params[:id])
		if @blog.update(blog_params)
			flash[:notice] = "ブログを更新しました"
			redirect_to blog_path(@blog.id)
		else
			render :edit
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		redirect_to blogs_path
	end

	private

	def blog_params
		params.require(:blog).permit(:title, :body)
	end

	def correct_blog
		blog = Blog.find(params[:id])
		user = blog.user
		unless user == current_user
			redirect_to(user_path)
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]

	def index
		@user = current_user
		@users = User.all
	end

	def show
		@user = User.find_by(id: params[:id])
		@blogs = @user.blogs
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if @user.save
			flash[:notice] = "ゲーム実録々にご登録いただき、有難うございます！"
			redirect_to user_path(@user.id)
		else
			flash.now[:error]
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "設定が完了しました"
			redirect_to user_path(@user.id)
		else
			flash.now[:error]
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end

	def correct_user
		user = User.find(params[:id])

		unless user == current_user
		redirect_to(user_path(current_user))
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<div class="container">
	<div class="col-xs-4"></div>
	<div class="col-xs-5">
		<h1 class="sub-title">ブログの編集</h1>

		<!--コメントエラー-->

		<% if @blog.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@blog.errors.count, "件のエラーが発生しました") %></h2>

				<ul>
					<% @blog.errors.full_messages.each do |message| %>
						<li><% message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<!--コメントエラーここまで-->

		<!--form_for-->

		<%= form_for(@blog) do |f| %>

			<h4>Title</h4>
			<%= f.text_field :title %>

			<h4>text</h4>
			<%= f.text_area :body %><br>

			<%= f.submit '変更する' %>
		<% end %>

		<%= link_to "編集を取り消す", blog_path %>
	</div>
</div>

app/views/blogs/index.html.erb
<div class="container">
	<div class="col-xs-3"></div>
	<div class="col-xs-6">
		<h1 class="sub-title">みんなが投稿した記事</h1>
		<table class="table table-hover">
			<br>
			<br>
			<br>
			<p>このページは色んなユーザーの方々が投稿した記事の一覧です。</p>
			<thead>
			<tr>
				<th></th>
				<th></th>
			</tr>
		</thead>
			<tbody>
			<% @blogs.each do |blog| %>
				<tr>
					<td>
						<h4 class="blog-title"><%= link_to blog.title, blog_path(blog.id) %></h4>
					</td>
					<td>
						<p class="blog-updatetime"><%= blog.created_at %></p>
					</td>
					<td>
						<p class="blog-comment">コメント数:<%= blog.comments.count %>件</p>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/blogs/new.html.erb
<div class="container">
	<div class="col-xs-4"></div>
	<div class="col-xs-5">
		<h1 class="sub-title">新しい記録</h1>

		<!--コメントエラー-->

		<% if @blog.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@blog.errors.count, "件のエラーが発生しました") %></h2>

				<ul>
					<% @blog.errors.full_messages.each do |message| %>
						<li><% message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<!--コメントエラーここまで-->

<!--form_for-->

		<%= form_for(@blog) do |f| %>

		<h4>記事のタイトル</h4>
		<%= f.text_field :title %>

		<h4>本文</h4>
		<%= f.text_area :body %><br>

		<%= f.submit '投稿する' %>

		<% end %>

		<h3>ブログを投稿する際の注意</h3>
		<br>
		<li>誹謗中傷を目的とした投稿はしないように。</li>
	</div>
</div>

app/views/blogs/show.html.erb
<div class="container">
	<div class="col-xs-4"></div>
	<div class="col-xs-5">
		<h1 class="sub-title">ブログ</h1>
		<span>
			<h3 class="blog-title">
				<%= @blog.title %>
			</h3>
			<%= @blog.created_at.strftime('%Y/%m/%d') %>
		</span>
		<br>
		<br>
		<div class="blog-text">
			<%= @blog.body %>
		</div>
		</br>

		<ul>

			<p class="blog-date">
			<span>
				<% if @blog.user == current_user %>
				<%= link_to "ブログを編集する", edit_blog_path %>
				<%= link_to "削除", blog_path(@blog.id), method: :delete, "data-confirm" => "本当に消しますか？" %>
			<% end %>
			</span>
			<div class="comment">
				<p><%= @blog.blog_comments.count %>件コメント</p>
			</div>
			</p>
		</ul>
	</div>
</div>

<div class="container">
	<div class="col-xs-4"></div>
	<div class="col-xs-5">
		<h2 class="sub-title">コメント一覧</h2>
			<% if @comments.any? %>
				<% @blog.comments.each do |comment| %>
					<div class="comment-user">
						<p><%= link_to "#{blog_comment.user.name}さん", user_path(blog_comment.user.id) %>
						<%= blog_comment.comment_text %></p>
					</div>

					<span class= "comment-date"><%= blog_comment.created_at.strftime("%Y/%m/%d") %></span>
				<% end %>
			<% end %>
			</br>

		<!--コメント投稿フォーム-->

		</br>
		<!--コメントエラー-->

			<% if @comment.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@blog_comment.errors.count, "件のエラーが発生しました") %></h2>

					<ul>
						<% @blog_comment.errors.full_messages.each do |message| %>
							<li><% message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

		<!--コメントエラーここまで-->
		</br>
		<% if user_signed_in? %>
			<%= form_for [@blog, @blog_comment] do |f| %>

				<div class="row">
					<div class="col-sm-12">
						<%= f.text_area :comment_text, rows:'5', class: "form-control", placeholder:"コメントをここに" %>
					</div>
				</div>
				<br>
				<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
		<% end %>

	</div>
</div>
<div class="container">
	<div class="col-xs-4"></div>
	<div class="col-xs-5">

		<!--コメントフォームここまで-->

		<h5>コメントする際の注意点</h5>
		<p>記事、及びユーザーの誹謗中傷とする内容は禁止です。他のユーザーの迷惑にならないようコメントしてください。</br>
		万が一、不信なコメントを見かけましたら、管理人まで、お問い合わせください。</p>

	</div>
</div>

app/views/home/about.html.erb
<div class="container">
	<div class="col-xs-2"></div>
	<div class="col-xs-8">

		<% if user_signed_in? %>
		<p>ゲーム実録々へようこそ！<br>
			このサイトは、皆様がゲーム中にあった珍プレイ、攻略方法、ストーリー考察を共有できるサイトです！<br>
			皆様が快適にご利用いただけますよう、ルールを守ってご利用ください。<br>
		<% else %>
			<p>ゲーム実録々へようこそ！<br>
			このサイトは、皆様がゲーム中にあった珍プレイ、攻略方法、ストーリー考察を共有できるサイトです！<br>
			まずは、新規登録をしてみましょう！<br>
		</p>
		<% end %>
	</div>
</div>

app/views/home/top.html.erb
<div class="container">
	<div class="col-xs-1"></div>
	<div class="col-xs-9">
		<div class="main-visual">
			<%= image_tag('rokuroku-mv.jpg')  %>
		<p>ゲーム実録々へようこそ！
		</p>
	</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game_jisturokuroku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <div class="col-xs-3">
          <%= link_to image_tag("logo.jpg"), root_path %>
        </div>
        <div class="col-xs-6"></div>
          <div class="nav navbar-right">
            <ul class="nav-nav-field">
              <br>
              <br>

              <!--サインインしているかしていないかによってメニューの表記が変わる。else以降のコードは非ログイン状態-->

              <% if user_signed_in? %>

                <li class="current">
                  <%= link_to 'About', about_path %>
                </li>
                <li>
                  <%= link_to "マイページ", user_path(current_user) %>
                </li>
                <li>
                  <%= link_to '新規作成', new_blog_path %>
                </li>

                <li>
                  <%= link_to 'ユーザー一覧', users_path %>
                </li>

                <li>
                  <%= link_to 'みんなが投稿した記事をみる', blogs_path %>
                </li>

                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>

                <li class="current">
                  <%= link_to 'About', about_path %>
                </li>
                <li>
                  <%= link_to "ログイン", new_user_session_path %>
                </li>
                <li>
                  <%= link_to "新規登録", new_user_registration_path %>
                </li>
              <% end %>

              <!--メニューここまで-->

            </ul>
          </div>
        </div>
      </header>
      </div>
    <%= yield %>
    <footer>
      <div id="footer">
        <div class="container">
          <div class="col-xs-5">
            <div class="footer-text">
              <h6>お借りした写真</h6>
              <p class="footer-text">
                <%= link_to "写真AC様", "https://www.photo-ac.com/" %><br>
                <%= link_to "いらすとや様", "https://www.irasutoya.com/" %>
              </p>
            </div>
          </div>
          <div class="col-xs-2">
            <p class="footer-text">ゲーム実録々</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="col-xs-5"></div>
	<div class="col-xs-5">
		<h2>ユーザー設定</h2>
		<div class="user-setting">

		<!--コメントエラー-->

		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "件のエラーが発生しました") %></h2>

				<ul>
					<% @user.errors.full_messages.each do |message| %>
						<li><% message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<!--コメントエラーここまで-->

			<!--ユーザー設定-->
			<%= form_for(@user) do |f| %>
				<div class="field">
					<%= f.label :name %>
					<%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前" %>
				</div>
				<div class="field">
					<%= f.label :image %>
					<%= f.attachment_field :profile_image, class: "user_image" %>
				</div>

				<div class="field">
					<%= f.label :introduction %>
					<%= f.text_area :introduction, class: "introduction" %>
				</div>

				<div class="action">
				<%= f.submit "設定を変更する" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="col-xs-4"></div>
	<div class="col-xs-5">
		<h2>ユーザー一覧</h2>

		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td>
						<%= attachment_image_tag @user, :profile_image, :fill, 20, 20, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
					</td>
					<td>
						<%= user.name %>
					</td>
					<td>
						<%= link_to "気になる" , user_path(user.id)%>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="col-xs-1"></div>
	<div class="col-xs-3">
		<div class="user-bar">
			<div class="user-icon-space">
			<%= attachment_image_tag @user, :profile_image, :fill, 20, 20, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
			</div>
			<%= @user.name %>
			<%= link_to "設定", edit_user_path(@user.id) %>
			<br>
			<br>
			<br>
			<br>
			<br>
			<div class="introduction-space">
				<p>自己紹介<br>
					<%= @user.introduction %>
				</p>
			</div>
		</div>
	</div>
	<div class="col-xs-5">
		<h1 class="sub-title">ブログ一覧画面</h1>
		<thead>
			<tr>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<table class="table table-hover">
			<tbody>
				<% @blogs.each do |blog| %>
				<tr>
					<td>
						<h4 class="blog-title">
							<%= link_to blog_path(blog.id) do %>
								<% blog.title %>
							<% end %>
						</h4>
					</td>
					<td>
						<p class="blog-updatetime">
							<%= blog.created_at.strftime('%Y/%m/%d') %>
						</p>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>